services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-emp-container
    environment:
      MYSQL_ROOT_PASSWORD: Don@12345
      MYSQL_DATABASE: emp_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    build: .
    container_name: emp-app-container
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/emp_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql-db

volumes:
  mysql-data: